### ISSUE TITLE
Application form does not work on staging

### ISSUE THREAD

**Issue by DjordjeVujatovic** [commitdev/commit.dev-proto#158]
When the form is submitted on staging, you get a 403 error.

<img width="1792" alt="Screen Shot 2021-03-08 at 3 17 03 PM" src="https://user-images.githubusercontent.com/22405289/110394704-bbebc900-8021-11eb-89be-26a13a0b0dd6.png">

**Comment by superkhau** [comment]
we need a staging sheet to hook it up to cc @timothy-wan

**Comment by adriandelisle** [comment]
@superkhau This [production endpoint](https://github.com/commitdev/commit.dev/blob/launch/.circleci/config.yml#L192) will work though right?

**Comment by superkhau** [comment]
@adriandelisle It should, but it'll probably error out. We'll need to do a bit of work/hook it up to another document to make it work. Let's chat about this offline with @timothy-wan, should be easy.

**Comment by timothy-wan** [comment]
I already have a staging sheet hooked up for it here: https://docs.google.com/spreadsheets/d/13AR_khlSzpwfPyTP2rFqB802nh8l2nj7GUmgvosbM6Y/edit#gid=0
Gave the form a couple of tries and it has been working for me on commit-staging.dev. Maybe see if you can replicate it again now?

**Comment by timothy-wan** [comment]
Oh I get why the error happens for this. This route is behind a helix CORs whitelist where only `commit-staging.dev` is allowed. That's why it's always going to fail if you try from `launch.commit-staging.dev`. I think you can start to use `commit-staging.dev` as the stg env as you guys move forward now with @adriandelisle 's changes to the ci pipeline

**Comment by superkhau** [comment]
@timothy-wan Can we dump the launch subdomain then?

**Comment by timothy-wan** [comment]
I think so. The idea behind it when made it with Jason in the first place was to keep prelaunch and the post launch site separate. Since the post launch site is coming along and will take over the prelaunch, I don't see a reason why we will need two different stg envs. You can leave the launch subdomain and use it as for just running ci tests though.

**Comment by superkhau** [comment]
@timothy-wan We can use another sub-domain for that if that's the case -- ie. `ci.commit-staging.dev`. In any case, don't need to solve now, we can figure it out later.

**Comment by adriandelisle** [comment]
I updated so launch is now pushing to https://commit-staging.dev/ so we can test the apply flow with confidence.
