### ISSUE TITLE
feat: lint files names

### ISSUE THREAD

**Issue by superkhau** [commitdev/commit.dev-proto#18]
All files are currently using `kebab-case`. This should be automatically enforced on CI.

**Comment by jasondippel** [comment]
Some quick research on the eslint plugin currently used ([eslint-plugin-unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/filename-case.md)) to enforce `kebab-case` shows that it only supports this enforcement for file names and not folder names. Tested this locally with the current configuration and can confirm.

I looked for some options that we could just pull in and use and the best options I've found up to now is [eslint-plugin-folders](https://www.npmjs.com/package/eslint-plugin-folders). Not the most popular plugin though so there's some concerns about how well it's maintained / works. Since this isn't exactly mission-critical type stuff, I'm tempted to try it out.

@superkhau @julie-huang Would like to get your thoughts and opinions about the suggested lib and whether or not it should be used.

**Comment by julie-huang** [comment]
@jasondippel You're right, seems like eslint-plugin-folders isn't widely used nor maintained so I'm not sure if we should add this as an additional dependency. I don't think it's super important that we need to lint folder names for now. What do you think @superkhau?

**Comment by superkhau** [comment]
@jasondippel Thanks for digging into it. It's not enough of a bother now to add another dep -- let's just enforce it via PR reviews and see if https://github.com/sindresorhus/eslint-plugin-unicorn/issues/686 takes off (it's been 6 month already so it's most likely not a priority).
